export const TASK_ADD_REQUEST = 'TASK_ADD_REQUEST'
export const TASK_ADD_SUCCESS = 'TASK_ADD_SUCCESS'
export const TASK_ADD_FAIL = 'TASK_ADD_FAIL'
export const TASK_ADD_RESET = 'TASK_ADD_RESET'

export const TASK_LIST_REQUEST = 'TASK_LIST_REQUEST'
export const TASK_LIST_SUCCESS = 'TASK_LIST_SUCCESS'
export const TASK_LIST_FAIL = 'TASK_LIST_FAIL'

export const TASK_COMP_REQUEST = 'TASK_COMP_REQUEST'
export const TASK_COMP_SUCCESS = 'TASK_COMP_SUCCESS'
export const TASK_COMP_FAIL = 'TASK_COMP_FAIL'
export const TASK_COMP_RESET = 'TASK_COMP_RESET'

export const TASK_DEL_REQUEST = 'TASK_DEL_REQUEST'
export const TASK_DEL_SUCCESS = 'TASK_DEL_SUCCESS'
export const TASK_DEL_FAIL = 'TASK_DEL_FAIL'
export const TASK_DEL_RESET = 'TASK_DEL_RESET'
